### ISSUE TITLE
privateKeyToAccount in code?

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting-alpha#6]
https://github.com/voteflux/voting-alpha/blob/04888ede04575aa2de2cf8b9a42c1d3ee9996b34/stack/app/members/api/handlers.py#L258

I thought I better check, should this be hidden as an env var?

**Comment by XertroV** [comment]
The line above:
`def tests(loop):`

:P

**Comment by KipCrossing** [comment]
Thought I'd check
